name: configure gpu
runs:
  using: "composite"
  steps:
    - name: Print environment
      run: |
        echo "${{ steps.cuda-toolkit.outputs.cuda }}"
        echo "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
        nvcc -V
        sudo apt install ninja-build
        pip install meson
        meson --version
        ninja --version
        g++ --version
      shell: bash
    - name: Configure
      run: meson setup build/ --buildtype=plain --warnlevel=2 -Dgpu=true
      shell: bash
