name: cpu (build & test)
run-name: ${{ github.actor }} is building & testing for cpu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  MAKEFLAGS: --no-print-directory
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Print environment
        run: |
          pip install meson
          meson --version
          g++ --version
      - name: Configure
        run: meson setup build/ --buildtype=plain --warnlevel=2
      - name: Build tests
        run: meson compile -C build/ tests
      - name: Run tests
        run: meson test -C build/

  build-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Print environment
        run: |
          pip install meson
          meson --version
          g++ --version
      - name: Configure
        run: meson setup build/ --buildtype=plain --warnlevel=2
      - name: Build examples
        run: meson compile -C build/ examples

  build-and-test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Print environment
        run: |
          pip install meson
          meson --version
          g++ --version
      - name: Configure
        run: meson setup build/ --buildtype=plain --warnlevel=2
      - name: Build python bindings
        run: meson compile -C build/ python
      - name: Run python tests
        run: |
          pip install pytest numpy
          PYTHONPATH=./build/ginn-py/ pytest -s --color=yes ./ginn-py/test/
