name: cpu (build & test)
run-name: ${{ github.actor }} is building & testing for cpu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-cpu
      - name: Build tests
        run: meson compile -C build/ tests
      - name: Run tests
        run: meson test -C build/ -t 0

  build-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-cpu
      - name: Build examples
        run: meson compile -C build/ examples

  build-and-test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-cpu
      - name: Build python bindings
        run: meson compile -C build/ python
      - name: Run python tests
        run: |
          PYTHONPATH=./build/ginn-py/ pytest -s --color=yes ./ginn-py/test/
