name: gpu (build only)
run-name: ${{ github.actor }} is building for gpu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-gpu
      - name: Build tests
        run: meson compile -C build/ tests

  build-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-gpu
      - name: Build examples
        run: meson compile -C build/ examples

  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-gpu
      - name: Build python bindings
        run: meson compile -C build/ python
