name: gpu (build only)
run-name: ${{ github.actor }} is building for gpu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  setup-cuda:
    runs-on: ubuntu-latest
    steps:
      - name: Get cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.15
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
      - name: tmp
        run: |
          echo "${{ steps.cuda-toolkit.outputs.cuda }}"
          echo "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
          which nvcc
          nvcc -V
      - name: Cache CUDA
        uses: actions/cache/save@v4
        with:
          path: /usr/local/cuda-11.7
          key: cuda-11.7
          
  build-tests:
    needs: setup-cuda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache CUDA
        uses: actions/cache/restore@v4
        with:
          path: /usr/local/cuda-11.7
          key: cuda-11.7
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-gpu
      - name: Build tests
        run: meson compile -C build/ tests

  build-examples:
    needs: setup-cuda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache CUDA
        uses: actions/cache/restore@v4
        with:
          path: /usr/local/cuda-11.7
          key: cuda-11.7
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-gpu
      - name: Build examples
        run: meson compile -C build/ examples

  build-python:
    needs: setup-cuda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache CUDA
        uses: actions/cache/restore@v4
        with:
          path: /usr/local/cuda-11.7
          key: cuda-11.7
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Bootstrap and configure
        uses: ./.github/actions/configure-gpu
      - name: Build python bindings
        run: meson compile -C build/ python
